language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql CAKEPHP=2.3.10
  - DB=pgsql CAKEPHP=2.3.10
  - DB=mysql CAKEPHP=2.4.10
  - DB=pgsql CAKEPHP=2.4.10
  - DB=mysql CAKEPHP=2.5.5
  - DB=pgsql CAKEPHP=2.5.5

before_script:
  - composer install --dev
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - wget https://github.com/cakephp/cakephp/tarball/$CAKEPHP -O cake.tar.gz
  - tar xf cake.tar.gz
  - mv cakephp-cakephp-* ./cakephp
  - chmod -R 777 ./cakephp/app/tmp
  - echo "<?php
    App::build(array(
    'Plugin' => array('/home/travis/build/k1LoW/'),
    ));
    CakePlugin::loadAll();
    ini_set('include_path',  '/home/travis/build/k1LoW/Yasd/vendor/phpunit/phpunit' . PATH_SEPARATOR . ini_get('include_path'));
    " > cakephp/app/Config/bootstrap.php
  - mv Test/database.php cakephp/app/Config/database.php
  - cd ./cakephp

script:
  - ./lib/Cake/Console/cake test Yasd Model/Behavior/SoftDeletable --stderr
